### ISSUE TITLE
Исправить рецепт Galluim Arsenide/Fix recipe Galluim Arsenide and  Исправление дробления руд из Nether 2х => 4х/Fix crushing ore from Nether 2x => 4x

### ISSUE THREAD

**Issue by TheNucFus** [Spartak1997/GregTech5.09UnofficialBuild#12]
Добавить возможность крафта Galluim Arsenide, чтобы сделать SMD Diode
Вернуть увеличение выхода с руд, которые находятся в Nether. Вместо 2х, вход 4х при дроблении

**Comment by LokiGT** [comment]
А в чем проблема с арсенидом галлия?
