### ISSUE TITLE
Breach of GT++ Licensing

### ISSUE THREAD

**Issue by draknyte1** [Spartak1997/GregTech5.09UnofficialBuild#13]
So as I can see here, you didn't even reformat the code you stole from here - https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedGregtechItems.java#L241

Remove it, or I'll take this up with Github directly, for breach of licensing.

![image](https://user-images.githubusercontent.com/3060479/50403382-00b71c80-0796-11e9-98ee-4a6ab8fdb45f.png)

> Derivative Works
These modifications are provided freely and may be decompiled and modified for private use, either with a decompiler or a bytecode editor. Public use of modified or derivative versions is prohibited unless you are given specific written permission. Distribution of the source code, modified (including custom compilation) or otherwise, is prohibited by anyone except the author, except in the case of a derivative mod that has been given prior approval. Creating derivative works for commercial use is expressly forbidden and the owner reserves full right to seek damages.

**Comment by draknyte1** [comment]
I will happily review all 200+ commits for other content if you fail to comply, then reach out to Github.

**Comment by Spartak1997** [comment]
@draknyte1 sorry, if I prevented you https://github.com/Spartak1997/GregTech5.09UnofficialBuild/commit/8f7cad8ed3b43e8a97f3868b75a61f928cd331e0
