### ISSUE TITLE
Minefantasy, Tinker's Construct, and NEI crash

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Spartak1997/GregTech5.09UnofficialBuild#19]
This fork of GT5U crashes during loading if Minefantasy 2, Tinker's Construct, and Not Enough Items are installed, but Mine & Blade Battlegear 2 isn't. I believe this is caused by Battlegear integration that Dream Master added to the GTNH fork.

https://pastebin.com/FApUJtwL

**Comment by Spartak1997** [comment]
TiCon and other mods working excellent. Use it. In Gdisk you can download GT builds https://drive.google.com/open?id=1DrWsmHoJWRshcNDu9XOYtZ-LRLZ5YXAO

**Comment by bHXDgiuMa5yLHyC8** [comment]
I tested this with the latest release. 5.09.34.1 crashes if Minefantasy, Tinker's Construct, and NEI are all installed at once. Please check the pastebin. If you are having trouble understanding my English please leave the issue open.

**Comment by Spartak1997** [comment]
I checked it. I saw a problem in Minefantasy.
