### ISSUE TITLE
Некорректный бонусный выход industrial pulverizer

### ISSUE THREAD

**Issue by LokiGT** [Spartak1997/GregTech5.09UnofficialBuild#20]
1) Параметр oreprocessingoutputmultiplier не влияет на количество выхода побочного продукта (да я увеличиваю выход с одного блока для экономии времени) 
2) эндовые и незерные руды имеют такой же выход побочки как обычные, хотя должены иметь выход 2х.

**Comment by LokiGT** [comment]
Я про конфиг overpoweredstuff.cfg

**Comment by Spartak1997** [comment]
в последней версии это исправлено. Проверьте пожалуйста

**Comment by Spartak1997** [comment]
https://github.com/Spartak1997/GregTech5.09UnofficialBuild/commit/f4246a0ad58320d829709625d6eeced9681b2913

**Comment by LokiGT** [comment]
Я использую версию gregtech-5.09.34.1.jar с гугл драйва.

**Comment by LokiGT** [comment]
Сторонние моды же не могут на это повлиять?

**Comment by LokiGT** [comment]
Я именно про тини пайл руды, который в процессе промывки должен получатся

**Comment by LokiGT** [comment]
Могу скринов накидать, если нужно или ещё что

**Comment by LokiGT** [comment]
Изначально некорректно выразился... Я про бонус от промывки, я ставлю допустим через конфиг 8 крашед ор чтобы выходило, но бонус от промывки все равно 2 пыльки.

**Comment by Spartak1997** [comment]
а, так это все меняет. Данная машина никак не зависит от данного конфига, да и сомневаюсь, что и другие машины тоже.

**Comment by LokiGT** [comment]
Другие машины не зависят, потому что работают уже с крашед ор, выход которой увеличивается в соответствии с конфигом в марсераторе/пульлайзере. Но всетаки было бы хорошо получать   бонусную пыльку в соответствии с количеством полученной крашед ор, как было бы получено при обычной промывке.

**Comment by LokiGT** [comment]
Иначе данный конфиг теряет смысл, и лично для меня теряет смысл данный многоблок.

**Comment by LokiGT** [comment]
Хотя в теории тогда нужно будет увеличить количество промывочной жидкости в соответствии с выходом крашед ор...
