### ISSUE TITLE
Проблема с extruder shape

### ISSUE THREAD

**Issue by LokiGT** [Spartak1997/GregTech5.09UnofficialBuild#22]
Собственно сабж с формой кирки, топора и лопаты не работают в экструдере. Или это так задумано?

**Comment by LokiGT** [comment]
Ещё добавлю, шейп ротора с любым металлом имеет одинаковую стоимость в еу

**Comment by Spartak1997** [comment]
Что такое сабж?
 Стоитмость по энергии уже давняя проблема некоторых шаблонных рецептов. Возможно знаю как исправить данный недочет.
