### ISSUE TITLE
Phosphorus и apatite в кристаллическая форме

### ISSUE THREAD

**Issue by LokiGT** [Spartak1997/GregTech5.09UnofficialBuild#23]
Почему-то отсутствует прямой способ масерации в пыль, есть только шейплесс рецепт из блоков... Также вроде был рецепт в автоклаве.

**Comment by Spartak1997** [comment]
А вы пробывали сделать это? Такие рецепты грег может и не показывать

**Comment by LokiGT** [comment]
Похоже руки не из того места. Удалил конфиг и все стало нормально.
