### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Spartak1997/GregTech5.09UnofficialBuild#25]
https://github.com/Blood-Asp/GT5-Unofficial/issues/1370

https://github.com/Blood-Asp/GT5-Unofficial/issues/1357

https://github.com/Blood-Asp/GT5-Unofficial/issues/1377

https://github.com/Blood-Asp/GT5-Unofficial/issues/1412

https://github.com/bartimaeusnek/crops-plus-plus/issues/22

**Comment by bHXDgiuMa5yLHyC8** [comment]
Another idea: higher tier wires, connectors, capacitors, and transformers for Immersive Engineering. Ability to craft EV, IV, LuV, ZPM, and UV Immersive Engineering wires with GregTech components.

**Comment by bHXDgiuMa5yLHyC8** [comment]
add the new advanced chemicals in GTNH:

https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/31683427c25ab79a421c964c92d9f875ad567d3e

https://github.com/GTNewHorizons/NewHorizons/issues/4093

**Comment by Spartak1997** [comment]
Sorry, but I like add only new chem from bartworks. BUT it's another addon and I can broke something if change something else. About previously issues, maybe add new circuits looks interesting.

**Comment by Spartak1997** [comment]
@bHXDgiuMa5yLHyC8 https://github.com/Spartak1997/GregTech5.09UnofficialBuild/commit/7d20111d321ca99952a5f50d8f037e2fa2149a4f

**Comment by Spartak1997** [comment]
@bHXDgiuMa5yLHyC8 https://github.com/Spartak1997/GregTech5.09UnofficialBuild/commit/7d20111d321ca99952a5f50d8f037e2fa2149a4f

**Comment by bHXDgiuMa5yLHyC8** [comment]
Thank you.

**Comment by bHXDgiuMa5yLHyC8** [comment]
early game idea: Flint and sticks spawn on the ground like TerraFirmaCraft, and you can craft two pieces of flint into a hand axe, so you don't have to start the game by punching a tree (especially if you are in adventure mode).

https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D0%B1%D0%B8%D0%BB%D0%BE

late game idea:  a multiblock robotic surgery chamber, where the player can add or remove cybernetic implants that give various bonuses

**Comment by Spartak1997** [comment]
@bHXDgiuMa5yLHyC8 integration with bartworks https://github.com/Spartak1997/GregTech5.09UnofficialBuild/commit/54b923f93737921dd9727c9aaceb3ac18482e41e

**Comment by bHXDgiuMa5yLHyC8** [comment]
Will you add the Fusion Crafter to Spartak GT5U? It looks very good.

**Comment by Spartak1997** [comment]
Of course! But after fix ore generation
